= My sexual behaviour and boundaries
:sectlinks:
:sectanchors:

[[privacy]]
== Level of information disclosure

I agree to provide information about my current sexual partners and their STI status upfront to my new partners. I will also notify my current partners about all new partners. I require my partners to give me the information about their partners, level of risk in sexual interactions between them (I'm mostly concerned with non-barriered sex), and their STI status if they get tested regularly.

I will not disclose any of the mentioned to people who are not my sexual partners. One exception is that I'm totally fine with public displays of affection if the respective partner is okay with it too.

[[testing]]
== STI testing

I'm aiming to get tested for most common infections about every 6 months. Results, as well as sexual history, are exchanged during negotiation.

[[boundaries]]
== Boundaries

* Manual stimulation
** I'm ok doing it without any barriers, unless the person is known to have an infection other than HPV or herpes (not during an active outbreak and if it is treated)
** Ok even if person doesn't get tested regularly, but care must be taken to avoid transfering bodily fluids (i.e. washing hands afterwards)
* Oral sex (both ways)
** Ok to do without a barrier only if:
*** Person was tested for STIs within the last year with negative results
*** All partners of the person whom she had non-barriered oral or penetrational sex since the last test were also tested with negative results within the last year
* Penetration
** Only with a condom
